# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Injury.create(name: "Sprained Ankle", priority: 3)
Injury.create(name: "Concussion", priority: 7)
Injury.create(name: "Broken Arm", priority: 8)
Injury.create(name: "Minor Cut", priority: 2)
Injury.create(name: "Severe Bleeding", priority: 10)
Injury.create(name: "Burn (First Degree)", priority: 4)
Injury.create(name: "Burn (Second Degree)", priority: 6)
Injury.create(name: "Burn (Third Degree)", priority: 9)
Injury.create(name: "Dislocated Shoulder", priority: 7)
Injury.create(name: "Heart Attack", priority: 10)
Injury.create(name: "Fractured Rib", priority: 6)
Injury.create(name: "Poisoning", priority: 9)
Injury.create(name: "Allergic Reaction", priority: 8)
Injury.create(name: "Asthma Attack", priority: 7)
Injury.create(name: "Heat Stroke", priority: 9)
Injury.create(name: "Frostbite", priority: 6)
Injury.create(name: "Electric Shock", priority: 10)
Injury.create(name: "Hypothermia", priority: 8)
Injury.create(name: "Drowning", priority: 10)
Injury.create(name: "Stroke", priority: 10)
Injury.create(name: "Pneumonia", priority: 7)
Injury.create(name: "Appendicitis", priority: 8)
Injury.create(name: "Severe Abdominal Pain", priority: 8)
Injury.create(name: "Migraine", priority: 5)
Injury.create(name: "Seizure", priority: 9)
Injury.create(name: "Chest Pain", priority: 10)
Injury.create(name: "Dehydration", priority: 6)
Injury.create(name: "Back Pain", priority: 4)
Injury.create(name: "High Fever", priority: 6)
Injury.create(name: "Influenza", priority: 5)
Injury.create(name: "Other", priority: 5)
